### ISSUE TITLE
Xbox One Kinect Disable Temp Sensor video links are private

### ISSUE THREAD

**Issue by astronaut701** [KinectToVR/k2vr-docs#8]
Pretty much what the title says. I found that the link to YouTube showing how to disable the temp sensor is private and was curious about this as the fan in my Xbox One Kinect has never spun while it's been in use. ¯\_(ツ)_/¯

The private video link is found on these pages in the wiki.

- https://docs.k2vr.tech/en/one/common-issues/#the-temperature-sensor-is-a-ticking-time-bomb
- https://docs.k2vr.tech/en/one/troubleshooting/#temperature-sensor

If the video can't be fixed, I'd be up to pop open my Xbox One Kinect to have a poke at the temperature sensor.

**Comment by HimbeersaftLP** [comment]
Recent discoveries have shown us that the temperature sensor is probably not actually what was going bad in those cases, so maybe it's better if the video doesn't work

**Comment by astronaut701** [comment]
Alrighty, closing this then. Hopefully whatever is actually going wrong is found then. Thanks for the reply!
